server:
  port: 8081
  servlet:
    contextPath: /bingBao
    session:
      timeout: 30d
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: bing_bao
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  resources:
    static-locations: file:/opt/bingBao/static/
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: true
    prefix: file:/opt/bingBao/templates/
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    user:
      name: ${db-username}
      password: ${db-password}
  data:
    mongodb:
      uri: mongodb://${db-username}:${db-password}@localhost:27017
      name: bingBao
  redis:
    host: localhost            # Redis 服務器的主機名或 IP 地址
    port: 6379                 # Redis 服務器的端口號
    password: ${db-password}   # Redis 的密碼（如果有設定）
    ssl: false                 # 是否啟用 SSL（預設為 false）
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

line:
  bot:
    channel:
      access:
        token: ${channel-access-token}
      secret: ${channel-access-secret}

config:
  jsonPath: /opt/bingBao/static/js/
  globalDomain: https://gurula.cc/bingBao/
  picSavePath: /opt/bingBao/bingBao_images/
  aiPicSavePath: /opt/bingBao/ai_images/
  picShowPath: https://gurula.cc/bingBao/bingBao_images/
  aiPicShowPath: https://gurula.cc/bingBao/ai_images/
  fileSavePath: /opt/bingBao/bingBao_files/
  fileShowPath: https://gurula.cc/bingBao/bingBao_files/
  apiKey: ${openai-api-key}
  channelAccessToken: ${channel-access-token}